spring:
  application:
    name: mon-domaine-metier
  cloud:
    config:
      uri:
        - http://localhost:8888
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/nt_mon_domaine_db
    username: root
    password:

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
      
app:
  healty:
    message: Je suis demarré - from config server